version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - './src:/src/app'